### ISSUE TITLE
update to angular @ 13.x

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#251]
We are going to be upgrading the following projects to angular 13.x
This is both to provide compatibility for the newest angular release, as well as to mitigate security issue(s) creep in aging dependencies.

- [ ] - [rest-api-client-ng](https://github.com/Senzing/rest-api-client-ng/issues/78)
- [ ] - [sdk-components-ng](https://github.com/Senzing/sdk-components-ng/issues/251)
- [ ] - [sdk-graph-components](https://github.com/Senzing/sdk-graph-components/issues/99)
- [ ] - [entity search webapp](https://github.com/Senzing/entity-search-web-app/issues/230)
